require('dotenv').config();
const mongoose = require('mongoose');
const Location = require('../models/Location');

// Comprehensive list of Bangladesh Districts and their Upazilas/Thanas
// Based on official Bangladesh administrative divisions
const districtUpazilaData = [
  // Dhaka Division
  { district: 'Dhaka', upazila: 'Adabor Thana' },
  { district: 'Dhaka', upazila: 'Badda Thana' },
  { district: 'Dhaka', upazila: 'Bangshal Thana' },
  { district: 'Dhaka', upazila: 'Biman Bandar Thana' },
  { district: 'Dhaka', upazila: 'Cantonment Thana' },
  { district: 'Dhaka', upazila: 'Chak Bazar Thana' },
  { district: 'Dhaka', upazila: 'Darus Salam Thana' },
  { district: 'Dhaka', upazila: 'Demra Thana' },
  { district: 'Dhaka', upazila: 'Dhanmondi Thana' },
  { district: 'Dhaka', upazila: 'Gendaria Thana' },
  { district: 'Dhaka', upazila: 'Gulshan Thana' },
  { district: 'Dhaka', upazila: 'Hazaribagh Thana' },
  { district: 'Dhaka', upazila: 'Jatrabari Thana' },
  { district: 'Dhaka', upazila: 'Kafrul Thana' },
  { district: 'Dhaka', upazila: 'Kalabagan Thana' },
  { district: 'Dhaka', upazila: 'Kamrangir Char Thana' },
  { district: 'Dhaka', upazila: 'Khilgaon Thana' },
  { district: 'Dhaka', upazila: 'Khilkhet Thana' },
  { district: 'Dhaka', upazila: 'Kotwali Thana' },
  { district: 'Dhaka', upazila: 'Lalbagh Thana' },
  { district: 'Dhaka', upazila: 'Mirpur Model Thana' },
  { district: 'Dhaka', upazila: 'Mohammadpur Thana' },
  { district: 'Dhaka', upazila: 'Motijheel Thana' },
  { district: 'Dhaka', upazila: 'New Market Thana' },
  { district: 'Dhaka', upazila: 'Pallabi Thana' },
  { district: 'Dhaka', upazila: 'Paltan Thana' },
  { district: 'Dhaka', upazila: 'Ramna Thana' },
  { district: 'Dhaka', upazila: 'Rampura Thana' },
  { district: 'Dhaka', upazila: 'Sabujbagh Thana' },
  { district: 'Dhaka', upazila: 'Shah Ali Thana' },
  { district: 'Dhaka', upazila: 'Shahbagh Thana' },
  { district: 'Dhaka', upazila: 'Shahjahanpur Thana' },
  { district: 'Dhaka', upazila: 'Sher-e-Bangla Nagar Thana' },
  { district: 'Dhaka', upazila: 'Shyampur Thana' },
  { district: 'Dhaka', upazila: 'Sutrapur Thana' },
  { district: 'Dhaka', upazila: 'Tejgaon Thana' },
  { district: 'Dhaka', upazila: 'Tejgaon Industrial Area Thana' },
  { district: 'Dhaka', upazila: 'Turag Thana' },
  { district: 'Dhaka', upazila: 'Uttara Thana' },
  { district: 'Dhaka', upazila: 'Uttara West Thana' },
  { district: 'Dhaka', upazila: 'Uttarkhan Thana' },
  { district: 'Dhaka', upazila: 'Vatara Thana' },
  { district: 'Dhaka', upazila: 'Wari Thana' },
  { district: 'Dhaka', upazila: 'Dhamrai Upazila' },
  { district: 'Dhaka', upazila: 'Dohar Upazila' },
  { district: 'Dhaka', upazila: 'Keraniganj Upazila' },
  { district: 'Dhaka', upazila: 'Nawabganj Upazila' },
  { district: 'Dhaka', upazila: 'Savar Upazila' },

  { district: 'Gazipur', upazila: 'Gazipur Sadar Upazila' },
  { district: 'Gazipur', upazila: 'Kaliakair Upazila' },
  { district: 'Gazipur', upazila: 'Kaliganj Upazila' },
  { district: 'Gazipur', upazila: 'Kapasia Upazila' },
  { district: 'Gazipur', upazila: 'Sreepur Upazila' },

  { district: 'Kishoreganj', upazila: 'Austagram Upazila' },
  { district: 'Kishoreganj', upazila: 'Bajitpur Upazila' },
  { district: 'Kishoreganj', upazila: 'Bhairab Upazila' },
  { district: 'Kishoreganj', upazila: 'Hossainpur Upazila' },
  { district: 'Kishoreganj', upazila: 'Itna Upazila' },
  { district: 'Kishoreganj', upazila: 'Karimganj Upazila' },
  { district: 'Kishoreganj', upazila: 'Katiadi Upazila' },
  { district: 'Kishoreganj', upazila: 'Kishoreganj Sadar Upazila' },
  { district: 'Kishoreganj', upazila: 'Kuliarchar Upazila' },
  { district: 'Kishoreganj', upazila: 'Mithamain Upazila' },
  { district: 'Kishoreganj', upazila: 'Nikli Upazila' },
  { district: 'Kishoreganj', upazila: 'Pakundia Upazila' },
  { district: 'Kishoreganj', upazila: 'Tarail Upazila' },

  { district: 'Manikganj', upazila: 'Daulatpur Upazila' },
  { district: 'Manikganj', upazila: 'Ghior Upazila' },
  { district: 'Manikganj', upazila: 'Harirampur Upazila' },
  { district: 'Manikganj', upazila: 'Manikganj Sadar Upazila' },
  { district: 'Manikganj', upazila: 'Saturia Upazila' },
  { district: 'Manikganj', upazila: 'Shibalaya Upazila' },
  { district: 'Manikganj', upazila: 'Singair Upazila' },

  { district: 'Munshiganj', upazila: 'Gazaria Upazila' },
  { district: 'Munshiganj', upazila: 'Lauhajang Upazila' },
  { district: 'Munshiganj', upazila: 'Munshiganj Sadar Upazila' },
  { district: 'Munshiganj', upazila: 'Serajdikhan Upazila' },
  { district: 'Munshiganj', upazila: 'Sreenagar Upazila' },
  { district: 'Munshiganj', upazila: 'Tongibari Upazila' },

  { district: 'Narayanganj', upazila: 'Araihazar Upazila' },
  { district: 'Narayanganj', upazila: 'Bandar Upazila' },
  { district: 'Narayanganj', upazila: 'Narayanganj Sadar Upazila' },
  { district: 'Narayanganj', upazila: 'Rupganj Upazila' },
  { district: 'Narayanganj', upazila: 'Sonargaon Upazila' },

  { district: 'Narsingdi', upazila: 'Belabo Upazila' },
  { district: 'Narsingdi', upazila: 'Monohardi Upazila' },
  { district: 'Narsingdi', upazila: 'Narsingdi Sadar Upazila' },
  { district: 'Narsingdi', upazila: 'Palash Upazila' },
  { district: 'Narsingdi', upazila: 'Raipura Upazila' },
  { district: 'Narsingdi', upazila: 'Shibpur Upazila' },

  { district: 'Rajbari', upazila: 'Baliakandi Upazila' },
  { district: 'Rajbari', upazila: 'Goalunda Upazila' },
  { district: 'Rajbari', upazila: 'Pangsha Upazila' },
  { district: 'Rajbari', upazila: 'Rajbari Sadar Upazila' },
  { district: 'Rajbari', upazila: 'Kalukhali Upazila' },

  { district: 'Shariatpur', upazila: 'Bhedarganj Upazila' },
  { district: 'Shariatpur', upazila: 'Damudya Upazila' },
  { district: 'Shariatpur', upazila: 'Gosairhat Upazila' },
  { district: 'Shariatpur', upazila: 'Naria Upazila' },
  { district: 'Shariatpur', upazila: 'Shariatpur Sadar Upazila' },
  { district: 'Shariatpur', upazila: 'Zajira Upazila' },

  { district: 'Tangail', upazila: 'Basail Upazila' },
  { district: 'Tangail', upazila: 'Bhuapur Upazila' },
  { district: 'Tangail', upazila: 'Delduar Upazila' },
  { district: 'Tangail', upazila: 'Ghatail Upazila' },
  { district: 'Tangail', upazila: 'Gopalpur Upazila' },
  { district: 'Tangail', upazila: 'Kalihati Upazila' },
  { district: 'Tangail', upazila: 'Madhupur Upazila' },
  { district: 'Tangail', upazila: 'Mirzapur Upazila' },
  { district: 'Tangail', upazila: 'Nagarpur Upazila' },
  { district: 'Tangail', upazila: 'Sakhipur Upazila' },
  { district: 'Tangail', upazila: 'Tangail Sadar Upazila' },
  { district: 'Tangail', upazila: 'Dhanbari Upazila' },

  // Chittagong Division
  { district: 'Chittagong', upazila: 'Anwara Upazila' },
  { district: 'Chittagong', upazila: 'Banshkhali Upazila' },
  { district: 'Chittagong', upazila: 'Boalkhali Upazila' },
  { district: 'Chittagong', upazila: 'Chandanaish Upazila' },
  { district: 'Chittagong', upazila: 'Fatikchhari Upazila' },
  { district: 'Chittagong', upazila: 'Hathazari Upazila' },
  { district: 'Chittagong', upazila: 'Lohagara Upazila' },
  { district: 'Chittagong', upazila: 'Mirsharai Upazila' },
  { district: 'Chittagong', upazila: 'Patiya Upazila' },
  { district: 'Chittagong', upazila: 'Rangunia Upazila' },
  { district: 'Chittagong', upazila: 'Raozan Upazila' },
  { district: 'Chittagong', upazila: 'Sandwip Upazila' },
  { district: 'Chittagong', upazila: 'Satkania Upazila' },
  { district: 'Chittagong', upazila: 'Sitakunda Upazila' },
  { district: 'Chittagong', upazila: 'Akbar Shah Thana' },
  { district: 'Chittagong', upazila: 'Bakalia Thana' },
  { district: 'Chittagong', upazila: 'Bandar Thana' },
  { district: 'Chittagong', upazila: 'Bayazid Bostami Thana' },
  { district: 'Chittagong', upazila: 'Chandgaon Thana' },
  { district: 'Chittagong', upazila: 'Chawk Bazar Thana' },
  { district: 'Chittagong', upazila: 'Double Mooring Thana' },
  { district: 'Chittagong', upazila: 'EPZ Thana' },
  { district: 'Chittagong', upazila: 'Halishahar Thana' },
  { district: 'Chittagong', upazila: 'Karnaphuli Thana' },
  { district: 'Chittagong', upazila: 'Khulshi Thana' },
  { district: 'Chittagong', upazila: 'Kotwali Thana' },
  { district: 'Chittagong', upazila: 'Kulshi Thana' },
  { district: 'Chittagong', upazila: 'Pahartali Thana' },
  { district: 'Chittagong', upazila: 'Panchlaish Thana' },
  { district: 'Chittagong', upazila: 'Patenga Thana' },
  { district: 'Chittagong', upazila: 'Sadarghat Thana' },

  { district: 'Brahmanbaria', upazila: 'Akhaura Upazila' },
  { district: 'Brahmanbaria', upazila: 'Ashuganj Upazila' },
  { district: 'Brahmanbaria', upazila: 'Bancharampur Upazila' },
  { district: 'Brahmanbaria', upazila: 'Bijoynagar Upazila' },
  { district: 'Brahmanbaria', upazila: 'Brahmanbaria Sadar Upazila' },
  { district: 'Brahmanbaria', upazila: 'Kasba Upazila' },
  { district: 'Brahmanbaria', upazila: 'Nabinagar Upazila' },
  { district: 'Brahmanbaria', upazila: 'Nasirnagar Upazila' },
  { district: 'Brahmanbaria', upazila: 'Sarail Upazila' },

  { district: 'Chandpur', upazila: 'Chandpur Sadar Upazila' },
  { district: 'Chandpur', upazila: 'Faridganj Upazila' },
  { district: 'Chandpur', upazila: 'Haimchar Upazila' },
  { district: 'Chandpur', upazila: 'Haziganj Upazila' },
  { district: 'Chandpur', upazila: 'Kachua Upazila' },
  { district: 'Chandpur', upazila: 'Matlab Dakshin Upazila' },
  { district: 'Chandpur', upazila: 'Matlab Uttar Upazila' },
  { district: 'Chandpur', upazila: 'Shahrasti Upazila' },

  { district: 'Comilla', upazila: 'Barura Upazila' },
  { district: 'Comilla', upazila: 'Brahmanpara Upazila' },
  { district: 'Comilla', upazila: 'Burichang Upazila' },
  { district: 'Comilla', upazila: 'Chandina Upazila' },
  { district: 'Comilla', upazila: 'Chauddagram Upazila' },
  { district: 'Comilla', upazila: 'Comilla Sadar Upazila' },
  { district: 'Comilla', upazila: 'Comilla Sadar South Upazila' },
  { district: 'Comilla', upazila: 'Daudkandi Upazila' },
  { district: 'Comilla', upazila: 'Debidwar Upazila' },
  { district: 'Comilla', upazila: 'Homna Upazila' },
  { district: 'Comilla', upazila: 'Laksam Upazila' },
  { district: 'Comilla', upazila: 'Lalmai Upazila' },
  { district: 'Comilla', upazila: 'Meghna Upazila' },
  { district: 'Comilla', upazila: 'Monohargonj Upazila' },
  { district: 'Comilla', upazila: 'Muradnagar Upazila' },
  { district: 'Comilla', upazila: 'Nangalkot Upazila' },
  { district: 'Comilla', upazila: 'Titas Upazila' },

  { district: "Cox's Bazar", upazila: "Cox's Bazar Sadar Upazila" },
  { district: "Cox's Bazar", upazila: 'Chakaria Upazila' },
  { district: "Cox's Bazar", upazila: 'Kutubdia Upazila' },
  { district: "Cox's Bazar", upazila: 'Maheshkhali Upazila' },
  { district: "Cox's Bazar", upazila: 'Pekua Upazila' },
  { district: "Cox's Bazar", upazila: 'Ramu Upazila' },
  { district: "Cox's Bazar", upazila: 'Teknaf Upazila' },
  { district: "Cox's Bazar", upazila: 'Ukhia Upazila' },

  { district: 'Feni', upazila: 'Chhagalnaiya Upazila' },
  { district: 'Feni', upazila: 'Daganbhuiyan Upazila' },
  { district: 'Feni', upazila: 'Feni Sadar Upazila' },
  { district: 'Feni', upazila: 'Fulgazi Upazila' },
  { district: 'Feni', upazila: 'Parshuram Upazila' },
  { district: 'Feni', upazila: 'Sonagazi Upazila' },

  { district: 'Khagrachari', upazila: 'Dighinala Upazila' },
  { district: 'Khagrachari', upazila: 'Khagrachari Sadar Upazila' },
  { district: 'Khagrachari', upazila: 'Lakshmichhari Upazila' },
  { district: 'Khagrachari', upazila: 'Mahalchhari Upazila' },
  { district: 'Khagrachari', upazila: 'Manikchhari Upazila' },
  { district: 'Khagrachari', upazila: 'Matiranga Upazila' },
  { district: 'Khagrachari', upazila: 'Panchhari Upazila' },
  { district: 'Khagrachari', upazila: 'Ramgarh Upazila' },

  { district: 'Lakshmipur', upazila: 'Lakshmipur Sadar Upazila' },
  { district: 'Lakshmipur', upazila: 'Raipur Upazila' },
  { district: 'Lakshmipur', upazila: 'Ramganj Upazila' },
  { district: 'Lakshmipur', upazila: 'Ramgati Upazila' },
  { district: 'Lakshmipur', upazila: 'Kamalnagar Upazila' },

  { district: 'Noakhali', upazila: 'Begumganj Upazila' },
  { district: 'Noakhali', upazila: 'Chatkhil Upazila' },
  { district: 'Noakhali', upazila: 'Companiganj Upazila' },
  { district: 'Noakhali', upazila: 'Hatiya Upazila' },
  { district: 'Noakhali', upazila: 'Kabirhat Upazila' },
  { district: 'Noakhali', upazila: 'Noakhali Sadar Upazila' },
  { district: 'Noakhali', upazila: 'Senbagh Upazila' },
  { district: 'Noakhali', upazila: 'Sonaimuri Upazila' },
  { district: 'Noakhali', upazila: 'Subarnachar Upazila' },

  { district: 'Rangamati', upazila: 'Baghaichhari Upazila' },
  { district: 'Rangamati', upazila: 'Barkal Upazila' },
  { district: 'Rangamati', upazila: 'Belaichhari Upazila' },
  { district: 'Rangamati', upazila: 'Juraichhari Upazila' },
  { district: 'Rangamati', upazila: 'Kaptai Upazila' },
  { district: 'Rangamati', upazila: 'Kawkhali Upazila' },
  { district: 'Rangamati', upazila: 'Langadu Upazila' },
  { district: 'Rangamati', upazila: 'Naniarchar Upazila' },
  { district: 'Rangamati', upazila: 'Rajasthali Upazila' },
  { district: 'Rangamati', upazila: 'Rangamati Sadar Upazila' },

  { district: 'Bandarban', upazila: 'Alikadam Upazila' },
  { district: 'Bandarban', upazila: 'Bandarban Sadar Upazila' },
  { district: 'Bandarban', upazila: 'Lama Upazila' },
  { district: 'Bandarban', upazila: 'Naikhongchhari Upazila' },
  { district: 'Bandarban', upazila: 'Rowangchhari Upazila' },
  { district: 'Bandarban', upazila: 'Ruma Upazila' },
  { district: 'Bandarban', upazila: 'Thanchi Upazila' },

  // Rajshahi Division
  { district: 'Bogra', upazila: 'Adamdighi Upazila' },
  { district: 'Bogra', upazila: 'Bogra Sadar Upazila' },
  { district: 'Bogra', upazila: 'Dhunat Upazila' },
  { district: 'Bogra', upazila: 'Dhupchanchia Upazila' },
  { district: 'Bogra', upazila: 'Gabtali Upazila' },
  { district: 'Bogra', upazila: 'Kahaloo Upazila' },
  { district: 'Bogra', upazila: 'Nandigram Upazila' },
  { district: 'Bogra', upazila: 'Sariakandi Upazila' },
  { district: 'Bogra', upazila: 'Shajahanpur Upazila' },
  { district: 'Bogra', upazila: 'Sherpur Upazila' },
  { district: 'Bogra', upazila: 'Shibganj Upazila' },
  { district: 'Bogra', upazila: 'Sonatala Upazila' },

  { district: 'Joypurhat', upazila: 'Akkelpur Upazila' },
  { district: 'Joypurhat', upazila: 'Joypurhat Sadar Upazila' },
  { district: 'Joypurhat', upazila: 'Kalai Upazila' },
  { district: 'Joypurhat', upazila: 'Khetlal Upazila' },
  { district: 'Joypurhat', upazila: 'Panchbibi Upazila' },

  { district: 'Naogaon', upazila: 'Atrai Upazila' },
  { district: 'Naogaon', upazila: 'Badalgachhi Upazila' },
  { district: 'Naogaon', upazila: 'Dhamoirhat Upazila' },
  { district: 'Naogaon', upazila: 'Manda Upazila' },
  { district: 'Naogaon', upazila: 'Mahadebpur Upazila' },
  { district: 'Naogaon', upazila: 'Naogaon Sadar Upazila' },
  { district: 'Naogaon', upazila: 'Niamatpur Upazila' },
  { district: 'Naogaon', upazila: 'Patnitala Upazila' },
  { district: 'Naogaon', upazila: 'Porsha Upazila' },
  { district: 'Naogaon', upazila: 'Raninagar Upazila' },
  { district: 'Naogaon', upazila: 'Sapahar Upazila' },

  { district: 'Natore', upazila: 'Bagatipara Upazila' },
  { district: 'Natore', upazila: 'Baraigram Upazila' },
  { district: 'Natore', upazila: 'Gurudaspur Upazila' },
  { district: 'Natore', upazila: 'Lalpur Upazila' },
  { district: 'Natore', upazila: 'Natore Sadar Upazila' },
  { district: 'Natore', upazila: 'Singra Upazila' },

  { district: 'Chapainawabganj', upazila: 'Bholahat Upazila' },
  { district: 'Chapainawabganj', upazila: 'Chapainawabganj Sadar Upazila' },
  { district: 'Chapainawabganj', upazila: 'Gomastapur Upazila' },
  { district: 'Chapainawabganj', upazila: 'Nachole Upazila' },
  { district: 'Chapainawabganj', upazila: 'Shibganj Upazila' },

  { district: 'Pabna', upazila: 'Atgharia Upazila' },
  { district: 'Pabna', upazila: 'Bera Upazila' },
  { district: 'Pabna', upazila: 'Bhangura Upazila' },
  { district: 'Pabna', upazila: 'Chatmohar Upazila' },
  { district: 'Pabna', upazila: 'Faridpur Upazila' },
  { district: 'Pabna', upazila: 'Ishwardi Upazila' },
  { district: 'Pabna', upazila: 'Pabna Sadar Upazila' },
  { district: 'Pabna', upazila: 'Santhia Upazila' },
  { district: 'Pabna', upazila: 'Sujanagar Upazila' },

  { district: 'Rajshahi', upazila: 'Bagha Upazila' },
  { district: 'Rajshahi', upazila: 'Bagmara Upazila' },
  { district: 'Rajshahi', upazila: 'Charghat Upazila' },
  { district: 'Rajshahi', upazila: 'Durgapur Upazila' },
  { district: 'Rajshahi', upazila: 'Godagari Upazila' },
  { district: 'Rajshahi', upazila: 'Mohanpur Upazila' },
  { district: 'Rajshahi', upazila: 'Paba Upazila' },
  { district: 'Rajshahi', upazila: 'Puthia Upazila' },
  { district: 'Rajshahi', upazila: 'Tanore Upazila' },
  { district: 'Rajshahi', upazila: 'Boalia Thana' },
  { district: 'Rajshahi', upazila: 'Matihar Thana' },
  { district: 'Rajshahi', upazila: 'Rajpara Thana' },
  { district: 'Rajshahi', upazila: 'Shah Makhdum Thana' },

  { district: 'Sirajganj', upazila: 'Belkuchi Upazila' },
  { district: 'Sirajganj', upazila: 'Chauhali Upazila' },
  { district: 'Sirajganj', upazila: 'Kamarkhanda Upazila' },
  { district: 'Sirajganj', upazila: 'Kazipur Upazila' },
  { district: 'Sirajganj', upazila: 'Raiganj Upazila' },
  { district: 'Sirajganj', upazila: 'Shahjadpur Upazila' },
  { district: 'Sirajganj', upazila: 'Sirajganj Sadar Upazila' },
  { district: 'Sirajganj', upazila: 'Tarash Upazila' },
  { district: 'Sirajganj', upazila: 'Ullahpara Upazila' },

  // Khulna Division
  { district: 'Bagerhat', upazila: 'Bagerhat Sadar Upazila' },
  { district: 'Bagerhat', upazila: 'Chitalmari Upazila' },
  { district: 'Bagerhat', upazila: 'Fakirhat Upazila' },
  { district: 'Bagerhat', upazila: 'Kachua Upazila' },
  { district: 'Bagerhat', upazila: 'Mollahat Upazila' },
  { district: 'Bagerhat', upazila: 'Mongla Upazila' },
  { district: 'Bagerhat', upazila: 'Morrelganj Upazila' },
  { district: 'Bagerhat', upazila: 'Rampal Upazila' },
  { district: 'Bagerhat', upazila: 'Sarankhola Upazila' },

  { district: 'Chuadanga', upazila: 'Alamdanga Upazila' },
  { district: 'Chuadanga', upazila: 'Chuadanga Sadar Upazila' },
  { district: 'Chuadanga', upazila: 'Damurhuda Upazila' },
  { district: 'Chuadanga', upazila: 'Jibannagar Upazila' },

  { district: 'Jessore', upazila: 'Abhaynagar Upazila' },
  { district: 'Jessore', upazila: 'Bagherpara Upazila' },
  { district: 'Jessore', upazila: 'Chaugachha Upazila' },
  { district: 'Jessore', upazila: 'Jhikargachha Upazila' },
  { district: 'Jessore', upazila: 'Keshabpur Upazila' },
  { district: 'Jessore', upazila: 'Jessore Sadar Upazila' },
  { district: 'Jessore', upazila: 'Manirampur Upazila' },
  { district: 'Jessore', upazila: 'Sharsha Upazila' },

  { district: 'Jhenaidah', upazila: 'Harinakunda Upazila' },
  { district: 'Jhenaidah', upazila: 'Jhenaidah Sadar Upazila' },
  { district: 'Jhenaidah', upazila: 'Kaliganj Upazila' },
  { district: 'Jhenaidah', upazila: 'Kotchandpur Upazila' },
  { district: 'Jhenaidah', upazila: 'Maheshpur Upazila' },
  { district: 'Jhenaidah', upazila: 'Shailkupa Upazila' },

  { district: 'Khulna', upazila: 'Batiaghata Upazila' },
  { district: 'Khulna', upazila: 'Dacope Upazila' },
  { district: 'Khulna', upazila: 'Dumuria Upazila' },
  { district: 'Khulna', upazila: 'Dighalia Upazila' },
  { district: 'Khulna', upazila: 'Koyra Upazila' },
  { district: 'Khulna', upazila: 'Paikgachha Upazila' },
  { district: 'Khulna', upazila: 'Phultala Upazila' },
  { district: 'Khulna', upazila: 'Rupsa Upazila' },
  { district: 'Khulna', upazila: 'Terokhada Upazila' },
  { district: 'Khulna', upazila: 'Daulatpur Thana' },
  { district: 'Khulna', upazila: 'Khalishpur Thana' },
  { district: 'Khulna', upazila: 'Khan Jahan Ali Thana' },
  { district: 'Khulna', upazila: 'Kotwali Thana' },
  { district: 'Khulna', upazila: 'Sonadanga Thana' },

  { district: 'Kushtia', upazila: 'Bheramara Upazila' },
  { district: 'Kushtia', upazila: 'Daulatpur Upazila' },
  { district: 'Kushtia', upazila: 'Khoksa Upazila' },
  { district: 'Kushtia', upazila: 'Kumarkhali Upazila' },
  { district: 'Kushtia', upazila: 'Kushtia Sadar Upazila' },
  { district: 'Kushtia', upazila: 'Mirpur Upazila' },

  { district: 'Magura', upazila: 'Magura Sadar Upazila' },
  { district: 'Magura', upazila: 'Mohammadpur Upazila' },
  { district: 'Magura', upazila: 'Shalikha Upazila' },
  { district: 'Magura', upazila: 'Sreepur Upazila' },

  { district: 'Meherpur', upazila: 'Gangni Upazila' },
  { district: 'Meherpur', upazila: 'Meherpur Sadar Upazila' },
  { district: 'Meherpur', upazila: 'Mujibnagar Upazila' },

  { district: 'Narail', upazila: 'Kalia Upazila' },
  { district: 'Narail', upazila: 'Lohagara Upazila' },
  { district: 'Narail', upazila: 'Narail Sadar Upazila' },

  { district: 'Satkhira', upazila: 'Assasuni Upazila' },
  { district: 'Satkhira', upazila: 'Debhata Upazila' },
  { district: 'Satkhira', upazila: 'Kalaroa Upazila' },
  { district: 'Satkhira', upazila: 'Kaliganj Upazila' },
  { district: 'Satkhira', upazila: 'Satkhira Sadar Upazila' },
  { district: 'Satkhira', upazila: 'Shyamnagar Upazila' },
  { district: 'Satkhira', upazila: 'Tala Upazila' },

  // Barisal Division
  { district: 'Barguna', upazila: 'Amtali Upazila' },
  { district: 'Barguna', upazila: 'Bamna Upazila' },
  { district: 'Barguna', upazila: 'Barguna Sadar Upazila' },
  { district: 'Barguna', upazila: 'Betagi Upazila' },
  { district: 'Barguna', upazila: 'Patharghata Upazila' },
  { district: 'Barguna', upazila: 'Taltali Upazila' },

  { district: 'Barisal', upazila: 'Agailjhara Upazila' },
  { district: 'Barisal', upazila: 'Babuganj Upazila' },
  { district: 'Barisal', upazila: 'Bakerganj Upazila' },
  { district: 'Barisal', upazila: 'Banaripara Upazila' },
  { district: 'Barisal', upazila: 'Barisal Sadar Upazila' },
  { district: 'Barisal', upazila: 'Gaurnadi Upazila' },
  { district: 'Barisal', upazila: 'Hizla Upazila' },
  { district: 'Barisal', upazila: 'Mehendiganj Upazila' },
  { district: 'Barisal', upazila: 'Muladi Upazila' },
  { district: 'Barisal', upazila: 'Wazirpur Upazila' },

  { district: 'Bhola', upazila: 'Bhola Sadar Upazila' },
  { district: 'Bhola', upazila: 'Burhanuddin Upazila' },
  { district: 'Bhola', upazila: 'Char Fasson Upazila' },
  { district: 'Bhola', upazila: 'Daulatkhan Upazila' },
  { district: 'Bhola', upazila: 'Lalmohan Upazila' },
  { district: 'Bhola', upazila: 'Manpura Upazila' },
  { district: 'Bhola', upazila: 'Tazumuddin Upazila' },

  { district: 'Jhalokati', upazila: 'Jhalokati Sadar Upazila' },
  { district: 'Jhalokati', upazila: 'Kathalia Upazila' },
  { district: 'Jhalokati', upazila: 'Nalchity Upazila' },
  { district: 'Jhalokati', upazila: 'Rajapur Upazila' },

  { district: 'Patuakhali', upazila: 'Bauphal Upazila' },
  { district: 'Patuakhali', upazila: 'Dashmina Upazila' },
  { district: 'Patuakhali', upazila: 'Dumki Upazila' },
  { district: 'Patuakhali', upazila: 'Galachipa Upazila' },
  { district: 'Patuakhali', upazila: 'Kalapara Upazila' },
  { district: 'Patuakhali', upazila: 'Mirzaganj Upazila' },
  { district: 'Patuakhali', upazila: 'Patuakhali Sadar Upazila' },
  { district: 'Patuakhali', upazila: 'Rangabali Upazila' },

  { district: 'Pirojpur', upazila: 'Bhandaria Upazila' },
  { district: 'Pirojpur', upazila: 'Kawkhali Upazila' },
  { district: 'Pirojpur', upazila: 'Mathbaria Upazila' },
  { district: 'Pirojpur', upazila: 'Nazirpur Upazila' },
  { district: 'Pirojpur', upazila: 'Nesarabad Upazila' },
  { district: 'Pirojpur', upazila: 'Pirojpur Sadar Upazila' },
  { district: 'Pirojpur', upazila: 'Zianagar Upazila' },

  // Sylhet Division
  { district: 'Habiganj', upazila: 'Ajmiriganj Upazila' },
  { district: 'Habiganj', upazila: 'Bahubal Upazila' },
  { district: 'Habiganj', upazila: 'Baniachang Upazila' },
  { district: 'Habiganj', upazila: 'Chunarughat Upazila' },
  { district: 'Habiganj', upazila: 'Habiganj Sadar Upazila' },
  { district: 'Habiganj', upazila: 'Lakhai Upazila' },
  { district: 'Habiganj', upazila: 'Madhabpur Upazila' },
  { district: 'Habiganj', upazila: 'Nabiganj Upazila' },
  { district: 'Habiganj', upazila: 'Sayestaganj Upazila' },

  { district: 'Moulvibazar', upazila: 'Barlekha Upazila' },
  { district: 'Moulvibazar', upazila: 'Juri Upazila' },
  { district: 'Moulvibazar', upazila: 'Kamalganj Upazila' },
  { district: 'Moulvibazar', upazila: 'Kulaura Upazila' },
  { district: 'Moulvibazar', upazila: 'Moulvibazar Sadar Upazila' },
  { district: 'Moulvibazar', upazila: 'Rajnagar Upazila' },
  { district: 'Moulvibazar', upazila: 'Sreemangal Upazila' },

  { district: 'Sunamganj', upazila: 'Bishwamvarpur Upazila' },
  { district: 'Sunamganj', upazila: 'Chhatak Upazila' },
  { district: 'Sunamganj', upazila: 'Derai Upazila' },
  { district: 'Sunamganj', upazila: 'Dharampasha Upazila' },
  { district: 'Sunamganj', upazila: 'Dowarabazar Upazila' },
  { district: 'Sunamganj', upazila: 'Jagannathpur Upazila' },
  { district: 'Sunamganj', upazila: 'Jamalganj Upazila' },
  { district: 'Sunamganj', upazila: 'Shalla Upazila' },
  { district: 'Sunamganj', upazila: 'Sunamganj Sadar Upazila' },
  { district: 'Sunamganj', upazila: 'Tahirpur Upazila' },
  { district: 'Sunamganj', upazila: 'South Sunamganj Upazila' },

  { district: 'Sylhet', upazila: 'Balaganj Upazila' },
  { district: 'Sylhet', upazila: 'Beanibazar Upazila' },
  { district: 'Sylhet', upazila: 'Bishwanath Upazila' },
  { district: 'Sylhet', upazila: 'Companiganj Upazila' },
  { district: 'Sylhet', upazila: 'Dakshin Surma Upazila' },
  { district: 'Sylhet', upazila: 'Fenchuganj Upazila' },
  { district: 'Sylhet', upazila: 'Golapganj Upazila' },
  { district: 'Sylhet', upazila: 'Gowainghat Upazila' },
  { district: 'Sylhet', upazila: 'Jaintiapur Upazila' },
  { district: 'Sylhet', upazila: 'Kanaighat Upazila' },
  { district: 'Sylhet', upazila: 'Osmaninagar Upazila' },
  { district: 'Sylhet', upazila: 'Zakiganj Upazila' },
  { district: 'Sylhet', upazila: 'Sylhet Sadar Upazila' },

  // Rangpur Division
  { district: 'Dinajpur', upazila: 'Birampur Upazila' },
  { district: 'Dinajpur', upazila: 'Birganj Upazila' },
  { district: 'Dinajpur', upazila: 'Biral Upazila' },
  { district: 'Dinajpur', upazila: 'Bochaganj Upazila' },
  { district: 'Dinajpur', upazila: 'Chirirbandar Upazila' },
  { district: 'Dinajpur', upazila: 'Dinajpur Sadar Upazila' },
  { district: 'Dinajpur', upazila: 'Fulbari Upazila' },
  { district: 'Dinajpur', upazila: 'Ghoraghat Upazila' },
  { district: 'Dinajpur', upazila: 'Hakimpur Upazila' },
  { district: 'Dinajpur', upazila: 'Kaharole Upazila' },
  { district: 'Dinajpur', upazila: 'Khansama Upazila' },
  { district: 'Dinajpur', upazila: 'Nawabganj Upazila' },
  { district: 'Dinajpur', upazila: 'Parbatipur Upazila' },

  { district: 'Gaibandha', upazila: 'Fulchhari Upazila' },
  { district: 'Gaibandha', upazila: 'Gaibandha Sadar Upazila' },
  { district: 'Gaibandha', upazila: 'Gobindaganj Upazila' },
  { district: 'Gaibandha', upazila: 'Palashbari Upazila' },
  { district: 'Gaibandha', upazila: 'Sadullapur Upazila' },
  { district: 'Gaibandha', upazila: 'Saghata Upazila' },
  { district: 'Gaibandha', upazila: 'Sundarganj Upazila' },

  { district: 'Kurigram', upazila: 'Bhurungamari Upazila' },
  { district: 'Kurigram', upazila: 'Char Rajibpur Upazila' },
  { district: 'Kurigram', upazila: 'Chilmari Upazila' },
  { district: 'Kurigram', upazila: 'Fulbari Upazila' },
  { district: 'Kurigram', upazila: 'Kurigram Sadar Upazila' },
  { district: 'Kurigram', upazila: 'Nageshwari Upazila' },
  { district: 'Kurigram', upazila: 'Rajarhat Upazila' },
  { district: 'Kurigram', upazila: 'Raomari Upazila' },
  { district: 'Kurigram', upazila: 'Ulipur Upazila' },

  { district: 'Lalmonirhat', upazila: 'Aditmari Upazila' },
  { district: 'Lalmonirhat', upazila: 'Hatibandha Upazila' },
  { district: 'Lalmonirhat', upazila: 'Kaliganj Upazila' },
  { district: 'Lalmonirhat', upazila: 'Lalmonirhat Sadar Upazila' },
  { district: 'Lalmonirhat', upazila: 'Patgram Upazila' },

  { district: 'Nilphamari', upazila: 'Dimla Upazila' },
  { district: 'Nilphamari', upazila: 'Domar Upazila' },
  { district: 'Nilphamari', upazila: 'Jaldhaka Upazila' },
  { district: 'Nilphamari', upazila: 'Kishoreganj Upazila' },
  { district: 'Nilphamari', upazila: 'Nilphamari Sadar Upazila' },
  { district: 'Nilphamari', upazila: 'Saidpur Upazila' },

  { district: 'Panchagarh', upazila: 'Atwari Upazila' },
  { district: 'Panchagarh', upazila: 'Boda Upazila' },
  { district: 'Panchagarh', upazila: 'Debiganj Upazila' },
  { district: 'Panchagarh', upazila: 'Panchagarh Sadar Upazila' },
  { district: 'Panchagarh', upazila: 'Tetulia Upazila' },

  { district: 'Rangpur', upazila: 'Badarganj Upazila' },
  { district: 'Rangpur', upazila: 'Gangachara Upazila' },
  { district: 'Rangpur', upazila: 'Kaunia Upazila' },
  { district: 'Rangpur', upazila: 'Mithapukur Upazila' },
  { district: 'Rangpur', upazila: 'Pirgachha Upazila' },
  { district: 'Rangpur', upazila: 'Pirganj Upazila' },
  { district: 'Rangpur', upazila: 'Rangpur Sadar Upazila' },
  { district: 'Rangpur', upazila: 'Taraganj Upazila' },

  { district: 'Thakurgaon', upazila: 'Baliadangi Upazila' },
  { district: 'Thakurgaon', upazila: 'Haripur Upazila' },
  { district: 'Thakurgaon', upazila: 'Pirganj Upazila' },
  { district: 'Thakurgaon', upazila: 'Ranisankail Upazila' },
  { district: 'Thakurgaon', upazila: 'Thakurgaon Sadar Upazila' },

  // Mymensingh Division
  { district: 'Mymensingh', upazila: 'Bhaluka Upazila' },
  { district: 'Mymensingh', upazila: 'Dhobaura Upazila' },
  { district: 'Mymensingh', upazila: 'Fulbaria Upazila' },
  { district: 'Mymensingh', upazila: 'Gaffargaon Upazila' },
  { district: 'Mymensingh', upazila: 'Gauripur Upazila' },
  { district: 'Mymensingh', upazila: 'Haluaghat Upazila' },
  { district: 'Mymensingh', upazila: 'Ishwarganj Upazila' },
  { district: 'Mymensingh', upazila: 'Mymensingh Sadar Upazila' },
  { district: 'Mymensingh', upazila: 'Muktagachha Upazila' },
  { district: 'Mymensingh', upazila: 'Nandail Upazila' },
  { district: 'Mymensingh', upazila: 'Phulpur Upazila' },
  { district: 'Mymensingh', upazila: 'Trishal Upazila' },
  { district: 'Mymensingh', upazila: 'Tara Khanda Upazila' },

  { district: 'Jamalpur', upazila: 'Baksiganj Upazila' },
  { district: 'Jamalpur', upazila: 'Dewanganj Upazila' },
  { district: 'Jamalpur', upazila: 'Islampur Upazila' },
  { district: 'Jamalpur', upazila: 'Jamalpur Sadar Upazila' },
  { district: 'Jamalpur', upazila: 'Madarganj Upazila' },
  { district: 'Jamalpur', upazila: 'Melandaha Upazila' },
  { district: 'Jamalpur', upazila: 'Sarishabari Upazila' },

  { district: 'Netrokona', upazila: 'Atpara Upazila' },
  { district: 'Netrokona', upazila: 'Barhatta Upazila' },
  { district: 'Netrokona', upazila: 'Durgapur Upazila' },
  { district: 'Netrokona', upazila: 'Khaliajuri Upazila' },
  { district: 'Netrokona', upazila: 'Kalmakanda Upazila' },
  { district: 'Netrokona', upazila: 'Kendua Upazila' },
  { district: 'Netrokona', upazila: 'Madan Upazila' },
  { district: 'Netrokona', upazila: 'Mohanganj Upazila' },
  { district: 'Netrokona', upazila: 'Netrokona Sadar Upazila' },
  { district: 'Netrokona', upazila: 'Purbadhala Upazila' },

  { district: 'Sherpur', upazila: 'Jhenaigati Upazila' },
  { district: 'Sherpur', upazila: 'Nakla Upazila' },
  { district: 'Sherpur', upazila: 'Nalitabari Upazila' },
  { district: 'Sherpur', upazila: 'Sherpur Sadar Upazila' },
  { district: 'Sherpur', upazila: 'Sreebardi Upazila' },
];

async function importData() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ MongoDB Connected Successfully');

    // Delete all existing locations
    const deleteResult = await Location.deleteMany({});
    console.log(`🗑️  Deleted ${deleteResult.deletedCount} existing location records`);

    // Insert new data
    let inserted = 0;
    let skipped = 0;

    for (const item of districtUpazilaData) {
      try {
        await Location.create({
          district: item.district,
          upazila: item.upazila,
        });
        inserted++;
      } catch (error) {
        if (error.code === 11000) {
          skipped++;
        } else {
          console.error(`Error inserting ${item.district} - ${item.upazila}:`, error.message);
        }
      }
    }

    console.log(`\n✅ Import completed!`);
    console.log(`   Total records: ${districtUpazilaData.length}`);
    console.log(`   Inserted: ${inserted}`);
    console.log(`   Skipped (duplicates): ${skipped}`);

    // Show sample data
    const districts = await Location.distinct('district');
    console.log(`\n📊 Unique districts: ${districts.length}`);
    console.log(`Districts: ${districts.sort().join(', ')}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Import failed:', error);
    process.exit(1);
  }
}

importData();
